title: YOUR_NAME - Cybersecurity Researcher
description: Ethical Hacker | Bug Bounty | CVE Hunter
url: "https://test34.github.io"
baseurl: ""

theme: jekyll-theme-minimal

plugins:
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      image: /assets/profile.jpg   # your profile pic (optional)

header_pages:
  - about.md
